# Generated by Django 5.2.17 on 2026-08-19 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmmAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_unit', models.CharField(max_length=255, verbose_name='Unidade de Saúde')),
                ('effective_date', models.DateField(verbose_name='Data para Efetivação')),
                ('requester_name', models.CharField(max_length=255, verbose_name='Responsável pela Solicitação')),
                ('requester_role', models.CharField(max_length=255, verbose_name='Função do Responsável')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações (Opcional)')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('RETURNED', 'Retornado'), ('COMPLETED', 'Concluído')], default='OPEN', max_length=20, verbose_name='Status')),
                ('admin_observation', models.TextField(blank=True, null=True, verbose_name='Observação do Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmm_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CmmAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('current_quantity', models.IntegerField(verbose_name='Quantidade Atual')),
                ('new_quantity', models.IntegerField(verbose_name='Nova Quantidade')),
                ('supri_code', models.CharField(max_length=50, verbose_name='Código SUPRI')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestao.cmmadjustmentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_unit', models.CharField(max_length=255, verbose_name='Unidade Solicitante')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação (Opcional)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_REVIEW', 'Em Análise'), ('RETURNED', 'Retornado'), ('COMPLETED', 'Concluído')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_observation', models.TextField(blank=True, null=True, verbose_name='Observação do Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('cmm', models.IntegerField(default=0, verbose_name='CMM')),
                ('supri_code', models.CharField(max_length=50, verbose_name='Código SUPRI')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestao.medicationtransfer')),
            ],
        ),
        migrations.CreateModel(
            name='RhoGamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant_name', models.CharField(max_length=255, verbose_name='Nome Completo da Gestante')),
                ('cns', models.CharField(max_length=15, verbose_name='CNS')),
                ('coombs_date', models.DateField(verbose_name='Data do exame de Coombs Indireto')),
                ('exam_result', models.CharField(choices=[('POSITIVE', 'Positivo'), ('NEGATIVE', 'Negativo')], max_length=10, verbose_name='Resultado do Exame')),
                ('pregnancy_weeks', models.IntegerField(verbose_name='Semana atual de gravidez')),
                ('doc1', models.FileField(upload_to='rhogam_docs/', verbose_name='Documento Oficial / SUS')),
                ('doc2', models.FileField(upload_to='rhogam_docs/', verbose_name='Resultado Coombs Indireto')),
                ('doc3', models.FileField(upload_to='rhogam_docs/', verbose_name='Prescrição / Solicitação Médica')),
                ('doc4', models.FileField(upload_to='rhogam_docs/', verbose_name='Guia de solicitação da unidade')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_REVIEW', 'Em Análise'), ('RETURNED', 'Retornado'), ('COMPLETED', 'Concluído')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_observation', models.TextField(blank=True, null=True, verbose_name='Observação do Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhogam_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
