# Generated by Django 6.1 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RhoGamSubmission',
        ),
    ]
